"""
AWS Developer Associate (DVA-C02) question bank — Batch 3.
Additional questions to bring total to ~285. Focus on difficulty 3-5, filling topic gaps.
"""
import json, os
from collections import Counter

questions = []

# ══════════════════════════════════════════════════════════════════════════════
# DEVELOPMENT WITH AWS SERVICES — Difficulty 3-5 (advanced patterns)
# ══════════════════════════════════════════════════════════════════════════════
questions += [
  {"question_text":"A developer needs to implement a distributed lock to prevent multiple Lambda instances from processing the same resource simultaneously. What is the recommended approach?","options":["Use DynamoDB conditional writes with a TTL-based lock item that expires automatically","Use SQS FIFO queues with message group IDs to serialise access to the resource","Use Lambda reserved concurrency set to 1 to ensure only one instance runs at a time","Use ElastiCache Redis SETNX command with an expiration for the distributed lock"],"correct_answer":"Use DynamoDB conditional writes with a TTL-based lock item that expires automatically","explanation":"DynamoDB conditional PutItem (attribute_not_exists) creates a lock item atomically. TTL ensures the lock expires if the holder crashes. This is simpler than Redis for serverless architectures since DynamoDB is already serverless.","memory_technique":"DynamoDB lock = PutItem with attribute_not_exists condition + TTL. Atomic acquire, auto-expire on crash. Serverless-native distributed lock.","topic_area":"Development with AWS Services","difficulty_level":5,"it_context_mapping":"This is the distributed lock pattern — using conditional writes for mutual exclusion, similar to Redis Redlock but using DynamoDB."},
  {"question_text":"A developer's Lambda function needs to return a response to the caller immediately but continue processing in the background. How should they implement this?","options":["Use Lambda's built-in background processing by returning a response and continuing execution","Invoke a second Lambda function asynchronously before returning the response to the caller","Use Step Functions Express Workflow to return immediately and continue processing in subsequent states","Return the response and send remaining work to an SQS queue for a separate Lambda to process"],"correct_answer":"Return the response and send remaining work to an SQS queue for a separate Lambda to process","explanation":"Lambda freezes the execution environment after returning a response — background work won't complete reliably. Send remaining work to SQS (or invoke another Lambda async) before returning. The queue ensures the work is processed.","memory_technique":"Lambda freezes after response. No reliable background processing. Pattern: Return response + send work to SQS. Separate Lambda processes the queue.","topic_area":"Development with AWS Services","difficulty_level":4,"it_context_mapping":"This is the async task pattern — returning immediately to the caller while offloading work to a background processor via a queue."},
  {"question_text":"A developer is using DynamoDB single-table design and needs to query items across multiple entity types (orders and order items) for a given customer. What access pattern enables this?","options":["Use a Scan with a FilterExpression to find all items matching the customer ID","Use a Query with partition key = customer_id and sort key begins_with to retrieve related entities","Create separate GSIs for each entity type and query them independently","Use BatchGetItem to retrieve specific items by their full primary keys"],"correct_answer":"Use a Query with partition key = customer_id and sort key begins_with to retrieve related entities","explanation":"Single-table design uses composite sort keys (ORDER#123, ITEM#456). Query PK=customer_id returns all entities. Use begins_with(SK, 'ORDER#') to get only orders, or no SK condition to get everything for that customer.","memory_technique":"Single-table query: PK=customer_id, SK begins_with('ORDER#'). One query, multiple entity types. Hierarchical sort keys enable flexible access patterns.","topic_area":"Development with AWS Services","difficulty_level":4,"it_context_mapping":"Single-table design with composite sort keys is like a denormalised view — storing related entities together for efficient retrieval in a single query."},
  {"question_text":"A developer needs to implement a webhook receiver that must respond to the sender within 3 seconds (sender timeout) but the actual processing takes 30 seconds. What architecture handles this?","options":["Use API Gateway with a Lambda function that processes synchronously within the 3-second window","Use API Gateway with Lambda that immediately returns 200, sends the payload to SQS, and a separate Lambda processes it","Use API Gateway with a 30-second timeout configured to match the processing time","Use Application Load Balancer with a longer idle timeout to accommodate the 30-second processing"],"correct_answer":"Use API Gateway with Lambda that immediately returns 200, sends the payload to SQS, and a separate Lambda processes it","explanation":"The webhook receiver Lambda validates the payload, sends it to SQS, and immediately returns 200 (well within 3 seconds). A separate Lambda processes the message from SQS without time pressure. This decouples receipt from processing.","memory_technique":"Webhook pattern: Receive → validate → queue → return 200 immediately. Process async from queue. Decouple receipt (fast) from processing (slow).","topic_area":"Development with AWS Services","difficulty_level":3,"it_context_mapping":"This is the async webhook pattern — acknowledging receipt immediately and processing asynchronously, common in payment and notification systems."},
  {"question_text":"A developer needs to implement server-sent events (SSE) for real-time updates to a web client. Lambda functions are stateless and can't maintain long-lived connections. What AWS service enables this?","options":["API Gateway WebSocket API with a Lambda function that pushes updates to connected clients","AWS AppSync with GraphQL subscriptions that push updates over WebSocket connections","Amazon SNS with HTTP/S endpoint subscriptions that push to the client's callback URL","CloudWatch Events with a rule that triggers client notifications via Lambda"],"correct_answer":"AWS AppSync with GraphQL subscriptions that push updates over WebSocket connections","explanation":"AppSync subscriptions provide managed real-time updates over WebSocket. When data changes (via mutation), AppSync automatically pushes updates to all subscribed clients. No connection management needed — AppSync handles it.","memory_technique":"Real-time updates to clients = AppSync subscriptions. Managed WebSocket. Mutation triggers push to subscribers. No connection management code.","topic_area":"Development with AWS Services","difficulty_level":4,"it_context_mapping":"AppSync subscriptions are like Socket.io rooms — clients subscribe to topics and receive real-time pushes when data changes."},
  {"question_text":"A developer's application uses DynamoDB and needs to perform a complex aggregation (sum of order totals per customer per month). DynamoDB doesn't support aggregation queries. What is the best approach?","options":["Use DynamoDB Streams with Lambda to maintain pre-computed aggregates in a separate table","Perform a full table Scan and aggregate in application code on every request","Export DynamoDB data to S3 and use Athena for ad-hoc aggregation queries","Use DynamoDB PartiQL to write SQL-like aggregation queries directly"],"correct_answer":"Use DynamoDB Streams with Lambda to maintain pre-computed aggregates in a separate table","explanation":"DynamoDB Streams triggers Lambda on every write. The Lambda function updates pre-computed aggregates (monthly totals per customer) in a separate table or item. Reads are instant — just fetch the pre-computed value.","memory_technique":"DynamoDB aggregation = Pre-compute via Streams. Write triggers Lambda → update aggregate item. Reads are O(1). Materialised view pattern.","topic_area":"Development with AWS Services","difficulty_level":4,"it_context_mapping":"This is the materialised view pattern — pre-computing aggregates on write so reads are instant, common in event-sourced systems."},
  {"question_text":"A developer needs to implement a priority queue where high-priority messages are processed before low-priority ones. SQS doesn't natively support priority. What is the best approach?","options":["Use a single SQS FIFO queue with message group IDs representing priority levels","Create separate SQS queues per priority level and configure Lambda to poll high-priority first","Use SNS message attributes to tag priority and filter at the subscriber level","Use Step Functions to sort messages by priority before sending them to a single processing queue"],"correct_answer":"Create separate SQS queues per priority level and configure Lambda to poll high-priority first","explanation":"Use separate queues (high, medium, low priority). Configure Lambda event source mappings with different batch sizes or use a custom poller that checks high-priority first. This ensures high-priority messages are processed before low-priority ones.","memory_technique":"Priority queue on AWS = Multiple SQS queues by priority. Poll high first. Or: weighted processing (high gets more Lambda concurrency). SQS doesn't have native priority.","topic_area":"Development with AWS Services","difficulty_level":4,"it_context_mapping":"Multiple queues by priority is the standard pattern when the queue system doesn't support native priority — used in many production systems."},
]

# ══════════════════════════════════════════════════════════════════════════════
# SECURITY — Difficulty 3-5 (advanced scenarios)
# ══════════════════════════════════════════════════════════════════════════════
questions += [
  {"question_text":"A developer's application uses API Gateway with a Lambda authorizer. They need to pass the authenticated user's ID to the backend Lambda without the backend re-validating the token. How?","options":["The Lambda authorizer returns a policy with context variables that API Gateway passes to the backend in the request context","The backend Lambda must always re-validate the token independently for security","Store the user ID in a shared DynamoDB table that both the authorizer and backend read from","Pass the user ID as a query parameter that the authorizer appends to the request URL"],"correct_answer":"The Lambda authorizer returns a policy with context variables that API Gateway passes to the backend in the request context","explanation":"Lambda authorizers can return context key-value pairs alongside the IAM policy. API Gateway passes these in event.requestContext.authorizer. The backend trusts these values since they come from the authorizer, not the client.","memory_technique":"Authorizer context = Trusted metadata passed to backend. Authorizer sets userId, role, etc. Backend reads from requestContext.authorizer. No re-validation needed.","topic_area":"Security","difficulty_level":4,"it_context_mapping":"Authorizer context is like request attributes set by authentication middleware — trusted metadata available to downstream handlers."},
  {"question_text":"A developer needs to implement token refresh for a mobile app using Cognito. The access token expires in 1 hour. How should the app handle expiration without forcing re-login?","options":["Store the user's password and automatically re-authenticate when the token expires","Use the refresh token to obtain new access and ID tokens without user interaction","Request access tokens with a longer expiration time (24 hours) to reduce refresh frequency","Implement a background timer that refreshes the token 5 minutes before expiration using the ID token"],"correct_answer":"Use the refresh token to obtain new access and ID tokens without user interaction","explanation":"Cognito issues a refresh token (valid for 30 days by default) alongside access/ID tokens. When the access token expires, the app sends the refresh token to Cognito's token endpoint to get new tokens silently — no re-login needed.","memory_technique":"Refresh token = Silent re-auth. Access token expires (1hr) → send refresh token → get new access token. No password needed. Refresh token valid 30 days.","topic_area":"Security","difficulty_level":3,"it_context_mapping":"Refresh tokens are the standard OAuth2 pattern — long-lived tokens that obtain new short-lived access tokens without user interaction."},
  {"question_text":"A developer needs to restrict a Lambda function so it can only be invoked from a specific VPC (not from the internet or other VPCs). How should they implement this?","options":["Place the Lambda function inside the VPC — this automatically restricts invocation to that VPC only","Use a Lambda resource-based policy with a condition on aws:SourceVpc to restrict invocations to the specific VPC","Configure the Lambda function's security group to only allow inbound traffic from the VPC CIDR","Use IAM policy conditions on the caller's role to restrict where they can invoke Lambda from"],"correct_answer":"Use a Lambda resource-based policy with a condition on aws:SourceVpc to restrict invocations to the specific VPC","explanation":"Lambda resource policies support VPC conditions (aws:SourceVpc, aws:SourceVpce). This restricts who can invoke the function based on the network origin — only requests from the specified VPC or VPC endpoint are allowed.","memory_technique":"aws:SourceVpc condition on Lambda resource policy = Only callable from that VPC. Network-level invocation restriction. Not the same as Lambda being IN a VPC.","topic_area":"Security","difficulty_level":5,"it_context_mapping":"VPC-based invocation restrictions are like network segmentation — ensuring services can only be called from trusted network locations."},
  {"question_text":"A developer is implementing a zero-trust architecture where every service call must be authenticated and authorised, even within the same AWS account. What combination of AWS features enables this?","options":["VPC security groups that restrict traffic between services at the network level","IAM roles with least-privilege policies + resource-based policies on every service + VPC endpoints for private communication","AWS PrivateLink between all services to ensure encrypted communication","AWS Service Mesh with App Mesh for mTLS between all service components"],"correct_answer":"IAM roles with least-privilege policies + resource-based policies on every service + VPC endpoints for private communication","explanation":"Zero-trust on AWS: (1) Each service has its own IAM role with minimal permissions. (2) Resource-based policies on Lambda/SQS/S3 restrict which roles can access them. (3) VPC endpoints keep traffic private. Every call is authenticated via SigV4.","memory_technique":"Zero-trust on AWS = IAM everywhere. Each service has unique role. Resource policies restrict callers. VPC endpoints for private paths. SigV4 authenticates every call.","topic_area":"Security","difficulty_level":5,"it_context_mapping":"Zero-trust with IAM is like mTLS service mesh — every service-to-service call is authenticated and authorised, regardless of network location."},
  {"question_text":"A developer's Lambda function needs to access resources in two different AWS accounts (read S3 in Account A, write DynamoDB in Account B). How should they configure permissions?","options":["Create a single IAM role that has cross-account permissions to both accounts","Have the Lambda assume different roles for each account using STS AssumeRole — one role per account","Use resource-based policies on both the S3 bucket and DynamoDB table to allow the Lambda's role","Store access keys for both accounts in Secrets Manager and use them directly"],"correct_answer":"Have the Lambda assume different roles for each account using STS AssumeRole — one role per account","explanation":"The Lambda function assumes a role in Account A for S3 access, then assumes a different role in Account B for DynamoDB access. Each role has minimal permissions for its specific task. The Lambda's execution role needs sts:AssumeRole permission for both target roles.","memory_technique":"Multi-account access = AssumeRole per account. Lambda role → AssumeRole(Account A role) for S3 → AssumeRole(Account B role) for DynamoDB. Separate credentials per account.","topic_area":"Security","difficulty_level":4,"it_context_mapping":"Multi-account role assumption is like federated identity across domains — obtaining separate credentials for each trust boundary."},
  {"question_text":"A developer needs to ensure that all data written to an SQS queue is encrypted and that only specific Lambda functions can decrypt and read the messages. What should they configure?","options":["Enable SQS SSE with a customer-managed KMS key and grant decrypt permission only to the consumer Lambda's execution role","Use client-side encryption in the producer and share the encryption key via Secrets Manager with consumers","Enable SQS SSE with the AWS-managed SQS key (aws/sqs) for automatic encryption","Configure the SQS queue policy to only allow specific Lambda functions to receive messages"],"correct_answer":"Enable SQS SSE with a customer-managed KMS key and grant decrypt permission only to the consumer Lambda's execution role","explanation":"SQS SSE with a customer-managed KMS key encrypts messages at rest. The KMS key policy grants kms:Decrypt only to specific Lambda execution roles. Other roles can't read messages even if they have SQS:ReceiveMessage permission — they can't decrypt.","memory_technique":"SQS SSE + customer KMS key = Encryption + access control. KMS key policy controls who can decrypt. Even with SQS access, no decrypt = can't read messages. Double lock.","topic_area":"Security","difficulty_level":4,"it_context_mapping":"KMS-based access control is like encryption-based authorization — even with network access, you need the decryption key to read the data."},
  {"question_text":"A developer discovers that their application's Cognito User Pool has been targeted by a credential stuffing attack (thousands of failed login attempts from different IPs). What Cognito feature helps mitigate this?","options":["Enable Cognito Advanced Security Features with adaptive authentication and compromised credentials detection","Implement a custom Lambda trigger that blocks IPs after 5 failed attempts","Enable MFA for all users which prevents credential stuffing entirely","Configure API Gateway WAF rules to block requests from known bot IP ranges"],"correct_answer":"Enable Cognito Advanced Security Features with adaptive authentication and compromised credentials detection","explanation":"Cognito Advanced Security uses ML to detect unusual sign-in attempts (new device, new location, impossible travel). It can require additional verification (MFA challenge) for risky attempts and block compromised credentials found in public breaches.","memory_technique":"Cognito Advanced Security = ML-based threat detection. Risk scoring per login attempt. Adaptive MFA challenges. Compromised credential checking. Blocks credential stuffing.","topic_area":"Security","difficulty_level":4,"it_context_mapping":"Cognito Advanced Security is like adaptive authentication in enterprise IAM — using risk signals to step up authentication requirements."},
]

# ══════════════════════════════════════════════════════════════════════════════
# DEPLOYMENT — Difficulty 3-5 (advanced scenarios)
# ══════════════════════════════════════════════════════════════════════════════
questions += [
  {"question_text":"A developer's SAM application has a Lambda function that needs different environment variables in dev vs prod, but the function code is identical. What is the cleanest way to manage this in the SAM template?","options":["Use SAM template Conditions to conditionally set environment variables based on a parameter","Use Mappings with FindInMap to look up environment-specific values based on a stage parameter","Use Globals section to set default environment variables that apply to all functions","Create separate template files for each environment with different hardcoded values"],"correct_answer":"Use Mappings with FindInMap to look up environment-specific values based on a stage parameter","explanation":"Mappings define a lookup table in the template. A Stage parameter (dev/prod) selects the right values via FindInMap. This keeps all configuration in one template without conditions or external files.","memory_technique":"Mappings + FindInMap = Lookup table in template. Stage parameter selects values. One template, all environments. Cleaner than Conditions for simple value differences.","topic_area":"Deployment","difficulty_level":4,"it_context_mapping":"Mappings are like configuration lookup tables — selecting values based on a key, similar to switch statements for infrastructure configuration."},
  {"question_text":"A developer needs to implement a zero-downtime deployment for an ECS Fargate service. The new version has a database schema change that's backward-compatible. What deployment strategy should they use?","options":["Rolling update with minimum healthy percent 100% and maximum percent 200% — new tasks start before old ones stop","Blue/green deployment with CodeDeploy that shifts traffic after health checks pass on the new task set","Recreate deployment that stops all old tasks and starts new ones simultaneously","Canary deployment that routes 10% of traffic to new tasks for 5 minutes before full cutover"],"correct_answer":"Blue/green deployment with CodeDeploy that shifts traffic after health checks pass on the new task set","explanation":"ECS blue/green with CodeDeploy creates a new task set (green), runs health checks, then shifts traffic from old (blue) to new. If health checks fail, traffic stays on blue. Provides instant rollback by shifting traffic back.","memory_technique":"ECS blue/green = New task set → health check → traffic shift → old task set drained. Instant rollback = shift traffic back to blue. Zero downtime guaranteed.","topic_area":"Deployment","difficulty_level":4,"it_context_mapping":"ECS blue/green is like Kubernetes rolling deployments with readiness probes — new instances must be healthy before receiving traffic."},
  {"question_text":"A developer's CloudFormation template creates an S3 bucket with a specific name. When they try to update the bucket's name, CloudFormation wants to replace the bucket (delete and recreate). How can they prevent data loss?","options":["Add UpdateReplacePolicy: Retain to keep the old bucket when CloudFormation creates the new one","Use a CloudFormation stack policy to prevent updates to the S3 bucket resource","Add DeletionPolicy: Retain so the old bucket is preserved when CloudFormation removes it from the stack","Rename the bucket outside of CloudFormation and import it as a new resource"],"correct_answer":"Add DeletionPolicy: Retain so the old bucket is preserved when CloudFormation removes it from the stack","explanation":"When CloudFormation replaces a resource, it creates the new one first, then deletes the old one. DeletionPolicy: Retain prevents the deletion step — the old bucket (with data) is preserved but no longer managed by the stack.","memory_technique":"Resource replacement + DeletionPolicy: Retain = Old resource preserved with data. New resource created. Old one orphaned (not in stack anymore). Data safe.","topic_area":"Deployment","difficulty_level":4,"it_context_mapping":"DeletionPolicy: Retain during replacement is like a safety net — ensuring data-bearing resources aren't destroyed during infrastructure changes."},
  {"question_text":"A developer needs to implement a GitOps workflow where pushing to the main branch automatically deploys to production. The pipeline must include automated tests and a manual approval gate. What is the correct CodePipeline structure?","options":["Source (CodeCommit) → Build+Test (CodeBuild) → Manual Approval → Deploy (CodeDeploy/CloudFormation)","Source (CodeCommit) → Manual Approval → Build+Test (CodeBuild) → Deploy (CodeDeploy)","Source (CodeCommit) → Deploy (CodeDeploy) → Test (CodeBuild) → Manual Approval","Source (CodeCommit) → Build (CodeBuild) → Deploy to Staging → Test → Manual Approval → Deploy to Prod"],"correct_answer":"Source (CodeCommit) → Build+Test (CodeBuild) → Manual Approval → Deploy (CodeDeploy/CloudFormation)","explanation":"The pipeline: (1) Source detects push to main. (2) CodeBuild compiles and runs automated tests — if tests fail, pipeline stops. (3) Manual approval gate for human review. (4) Deploy to production only after tests pass AND human approves.","memory_technique":"Pipeline order: Source → Build+Test → Approve → Deploy. Tests gate approval. Approval gates deployment. Each stage must pass before the next. Fail fast.","topic_area":"Deployment","difficulty_level":3,"it_context_mapping":"This is the standard CI/CD pipeline pattern — automated quality gates followed by manual approval before production deployment."},
  {"question_text":"A developer needs to deploy a Lambda function that depends on a DynamoDB table. During deployment, the function must not be invoked until the table exists. How does CloudFormation handle this?","options":["CloudFormation deploys all resources simultaneously — the developer must add explicit DependsOn","CloudFormation automatically detects the dependency if the function references the table (via !Ref or !GetAtt) and creates the table first","The developer must use a two-stage deployment — deploy the table first, then deploy the function separately","CloudFormation requires a Custom Resource to verify the table exists before creating the function"],"correct_answer":"CloudFormation automatically detects the dependency if the function references the table (via !Ref or !GetAtt) and creates the table first","explanation":"CloudFormation builds a dependency graph from !Ref and !GetAtt references. If the Lambda function's environment variables reference the DynamoDB table (!Ref or !GetAtt), CloudFormation automatically creates the table first.","memory_technique":"CloudFormation implicit dependencies = !Ref and !GetAtt create the dependency graph automatically. No explicit DependsOn needed if you reference the resource.","topic_area":"Deployment","difficulty_level":3,"it_context_mapping":"Implicit dependency resolution is like a build system's dependency graph — automatically determining the correct order from declared references."},
  {"question_text":"A developer's Lambda function deployment package exceeds the 50MB zipped limit (250MB unzipped). The function uses large ML model files. What are their options?","options":["Split the function into multiple smaller functions that each contain part of the model","Use a Lambda Layer for the model files (up to 250MB total across all layers)","Use a Lambda container image (up to 10GB) that includes the model files","Use S3 to store the model and download it to /tmp (512MB-10GB) during function initialisation"],"correct_answer":"Use a Lambda container image (up to 10GB) that includes the model files","explanation":"Lambda container images support up to 10GB, far exceeding the 250MB ZIP limit. Package the model in the Docker image. Alternatively, download from S3 to /tmp (up to 10GB with ephemeral storage), but container images are simpler for static assets.","memory_technique":"Large dependencies: ZIP limit = 250MB. Container image = 10GB. /tmp ephemeral storage = up to 10GB. For static large files, container image is cleanest.","topic_area":"Deployment","difficulty_level":4,"it_context_mapping":"Lambda container images solve the same problem as custom Docker deployments — packaging large dependencies that exceed standard deployment limits."},
  {"question_text":"A developer needs to implement a multi-region active-active deployment for their serverless API. What combination of services enables this?","options":["Deploy the same SAM stack to multiple regions + Route 53 latency-based routing + DynamoDB Global Tables","Use CloudFront with multiple API Gateway origins in different regions for failover","Deploy to one region and use Global Accelerator to route traffic from all regions","Use API Gateway edge-optimised endpoints which automatically deploy to all edge locations"],"correct_answer":"Deploy the same SAM stack to multiple regions + Route 53 latency-based routing + DynamoDB Global Tables","explanation":"Active-active multi-region: (1) Deploy identical stacks to each region. (2) Route 53 latency routing sends users to the nearest region. (3) DynamoDB Global Tables replicate data across regions. Each region can serve all requests independently.","memory_technique":"Multi-region active-active = Same stack per region + Route 53 latency routing + Global Tables. Each region is independent. Nearest region serves the request.","topic_area":"Deployment","difficulty_level":5,"it_context_mapping":"Active-active multi-region is like a globally distributed system — each region can independently serve all traffic with data replicated between them."},
]

# ══════════════════════════════════════════════════════════════════════════════
# TROUBLESHOOTING AND OPTIMIZATION — Difficulty 3-5 (advanced)
# ══════════════════════════════════════════════════════════════════════════════
questions += [
  {"question_text":"A developer's Lambda function processes API Gateway requests. CloudWatch shows invocations but no log entries in the function's log group. What is the most likely cause?","options":["The Lambda function's execution role is missing logs:CreateLogGroup, logs:CreateLogStream, or logs:PutLogEvents permissions","CloudWatch Logs has a propagation delay — the logs will appear within 5 minutes","The function is crashing before any log statements execute due to an import error","API Gateway is caching responses and not actually invoking the Lambda function"],"correct_answer":"The Lambda function's execution role is missing logs:CreateLogGroup, logs:CreateLogStream, or logs:PutLogEvents permissions","explanation":"Lambda needs explicit CloudWatch Logs permissions in its execution role. Without logs:PutLogEvents, the function executes but can't write logs. The invocation metric still increments because the function runs — it just can't log.","memory_technique":"No logs but invocations exist = Missing log permissions. Execution role needs: logs:CreateLogGroup + logs:CreateLogStream + logs:PutLogEvents. Common when creating custom roles.","topic_area":"Troubleshooting and Optimization","difficulty_level":3,"it_context_mapping":"This is like a file permission issue — the application runs but can't write to the log file because it lacks write permissions."},
  {"question_text":"A developer's DynamoDB table has auto-scaling configured but they notice throttling during sudden traffic spikes that last only 2-3 minutes. Auto-scaling doesn't react fast enough. What should they do?","options":["Switch to on-demand capacity mode which handles spikes without scaling delays","Enable DynamoDB burst capacity which provides a buffer for short-duration spikes","Increase the auto-scaling target utilisation from 70% to 50% to provision more headroom","Pre-warm the table by running a load test before expected traffic spikes"],"correct_answer":"Switch to on-demand capacity mode which handles spikes without scaling delays","explanation":"DynamoDB auto-scaling has a 1-2 minute reaction time. For short spikes (2-3 minutes), the spike is over before scaling kicks in. On-demand mode handles spikes instantly (up to 2x previous peak) without any scaling delay.","memory_technique":"Short spikes + auto-scaling too slow = Switch to on-demand. On-demand reacts instantly (up to 2x peak). Auto-scaling needs 1-2 min to react. On-demand is better for unpredictable, spiky traffic.","topic_area":"Troubleshooting and Optimization","difficulty_level":4,"it_context_mapping":"This is the reactive vs. instant scaling tradeoff — auto-scaling reacts to metrics (delayed) while on-demand provisions instantly."},
  {"question_text":"A developer's Lambda function makes HTTPS calls to an external API. After deploying the function into a VPC (to access RDS), the external API calls start timing out. What happened?","options":["Lambda functions in a VPC cannot make any outbound internet calls — this is a hard limitation","The function needs a NAT Gateway in a public subnet to route internet traffic from the private subnet","The VPC's security group is blocking outbound HTTPS traffic on port 443","The function's ENI in the VPC has a conflicting IP address with the external API"],"correct_answer":"The function needs a NAT Gateway in a public subnet to route internet traffic from the private subnet","explanation":"Lambda functions in a VPC are placed in private subnets. They have no internet access by default. To reach external APIs, you need a NAT Gateway in a public subnet with a route from the private subnet. Alternatively, use VPC endpoints for AWS services.","memory_technique":"Lambda in VPC = No internet by default. Need NAT Gateway for external calls. Private subnet → NAT Gateway → Internet Gateway → Internet. Common gotcha when adding VPC to Lambda.","topic_area":"Troubleshooting and Optimization","difficulty_level":3,"it_context_mapping":"This is the same as any server in a private subnet — it needs a NAT gateway or proxy to reach the internet."},
  {"question_text":"A developer's application uses API Gateway REST API with Lambda proxy integration. They're seeing 'Execution failed due to configuration error: Malformed Lambda proxy response' in API Gateway logs. What is wrong?","options":["The Lambda function is returning a response object that doesn't match the proxy integration format (statusCode, headers, body)","The Lambda function's execution role doesn't have permission to be invoked by API Gateway","The API Gateway stage variables are misconfigured causing the wrong Lambda function to be invoked","The Lambda function is exceeding the 6MB response payload limit"],"correct_answer":"The Lambda function is returning a response object that doesn't match the proxy integration format (statusCode, headers, body)","explanation":"Lambda proxy integration requires a specific response format: {statusCode: number, headers: object, body: string}. If the function returns anything else (raw object, missing statusCode, non-string body), API Gateway returns 502 with this error.","memory_technique":"Malformed Lambda proxy response = Wrong return format. Must be: {statusCode: 200, headers: {}, body: JSON.stringify(data)}. Body must be a STRING. Common mistake: returning object instead of stringified JSON.","topic_area":"Troubleshooting and Optimization","difficulty_level":3,"it_context_mapping":"This is like a web framework requiring a specific response format — the handler must return the expected structure or the framework can't process it."},
  {"question_text":"A developer's Lambda function connected to an RDS database is experiencing connection exhaustion during traffic spikes. The database shows max_connections reached. What is the best solution?","options":["Increase the RDS instance size to allow more connections","Use RDS Proxy to pool and share database connections across Lambda invocations","Implement connection pooling in the Lambda function code using a global connection variable","Reduce Lambda concurrency to match the database's max_connections limit"],"correct_answer":"Use RDS Proxy to pool and share database connections across Lambda invocations","explanation":"Each Lambda instance opens its own database connection. At high concurrency (hundreds of instances), this exhausts RDS connections. RDS Proxy pools connections — many Lambda instances share a smaller pool of database connections.","memory_technique":"Lambda + RDS = Connection exhaustion at scale. Fix: RDS Proxy. Pools connections. 1000 Lambda instances → 50 DB connections via proxy. Multiplexing.","topic_area":"Troubleshooting and Optimization","difficulty_level":4,"it_context_mapping":"RDS Proxy is like PgBouncer or ProxySQL — a connection pooler that multiplexes many application connections over fewer database connections."},
  {"question_text":"A developer notices that their Lambda function's billed duration is always rounded up significantly. The function runs for 1.2ms but is billed for 1ms (minimum). They want to optimise cost for a function invoked millions of times. What should they consider?","options":["Lambda bills in 1ms increments with a 1ms minimum — the function is already at minimum cost per invocation","Reduce memory allocation to the minimum (128MB) since the function is so fast","Batch multiple operations into a single invocation to amortise the per-invocation overhead","The function is already optimally priced — focus on reducing invocation count instead"],"correct_answer":"Batch multiple operations into a single invocation to amortise the per-invocation overhead","explanation":"For very fast functions invoked millions of times, the per-request overhead (cold start amortisation, invocation cost) dominates. Batching multiple items per invocation (via SQS batch size) reduces total invocations and cost.","memory_technique":"Millions of tiny invocations = Per-invocation overhead dominates. Batch: process 10 items per invocation instead of 1. 10x fewer invocations. SQS batch size = easy batching.","topic_area":"Troubleshooting and Optimization","difficulty_level":5,"it_context_mapping":"Batching to amortise overhead is a universal optimisation pattern — reducing per-unit fixed costs by processing multiple items together."},
  {"question_text":"A developer's Step Functions workflow occasionally fails with 'States.Timeout' on a Lambda task that usually completes in 2 seconds. The Lambda function itself doesn't timeout. What is happening?","options":["Step Functions has a default task timeout of 60 seconds that the Lambda is exceeding","The Step Functions task has a TimeoutSeconds configured that's being exceeded due to Lambda cold starts or throttling","Step Functions is timing out waiting for the Lambda service to acknowledge the invocation request","The Lambda function is returning a response that Step Functions can't parse, causing a timeout"],"correct_answer":"The Step Functions task has a TimeoutSeconds configured that's being exceeded due to Lambda cold starts or throttling","explanation":"If a Task state has TimeoutSeconds set (e.g., 5 seconds) and the Lambda takes longer due to cold start or throttling retry, Step Functions raises States.Timeout. The Lambda itself didn't timeout — Step Functions' patience ran out.","memory_technique":"States.Timeout = Step Functions gave up waiting. Check TimeoutSeconds on the Task state. Cold starts or throttling can push Lambda past the Step Functions timeout. Set TimeoutSeconds > worst-case Lambda duration.","topic_area":"Troubleshooting and Optimization","difficulty_level":4,"it_context_mapping":"This is like a client-side timeout — the orchestrator gives up waiting even though the service would eventually respond."},
  {"question_text":"A developer's application uses CloudFront in front of API Gateway. They notice that authenticated API responses are being cached and served to different users. What is the configuration error?","options":["CloudFront is caching based on URL only — they need to include the Authorization header in the cache key","API Gateway's cache is enabled and not differentiating between users","CloudFront doesn't support caching authenticated content — they should bypass CloudFront for API calls","The Cache-Control headers from the Lambda function are incorrectly set to public"],"correct_answer":"CloudFront is caching based on URL only — they need to include the Authorization header in the cache key","explanation":"By default, CloudFront caches based on URL path only. If authenticated responses vary by user, the Authorization header must be included in the cache key (or forwarded without caching). Otherwise, User A's response is served to User B.","memory_technique":"CloudFront caching authenticated APIs: Include Authorization header in cache key. Otherwise same URL = same cached response for all users. Or: set Cache-Control: private, no-store.","topic_area":"Troubleshooting and Optimization","difficulty_level":4,"it_context_mapping":"This is the classic CDN caching mistake — caching personalized content without varying on the authentication token."},
]

# ══════════════════════════════════════════════════════════════════════════════
# WRITE OUTPUT — Merge with existing questions
# ══════════════════════════════════════════════════════════════════════════════
out_path = os.path.join(os.path.dirname(__file__), "dva_questions.json")

# Load existing questions
existing = []
if os.path.exists(out_path):
    with open(out_path, "r", encoding="utf-8") as f:
        existing = json.load(f)

# Merge: add new questions that don't already exist (by question_text)
existing_texts = {q["question_text"] for q in existing}
new_count = 0
for q in questions:
    if q["question_text"] not in existing_texts:
        existing.append(q)
        existing_texts.add(q["question_text"])
        new_count += 1

# Write merged output
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(existing, f, indent=2, ensure_ascii=False)

diff_counts  = Counter(q["difficulty_level"] for q in existing)
topic_counts = Counter(q["topic_area"] for q in existing)
print(f"New questions added: {new_count}")
print(f"Total questions in file: {len(existing)}")
print("By difficulty:", dict(sorted(diff_counts.items())))
print("By topic:", dict(sorted(topic_counts.items())))
