"""
AWS Developer Associate (DVA-C02) question bank — Batch 4.
Final batch to bring total to ~285. Mixed difficulty 2-5.
"""
import json, os
from collections import Counter

questions = []

# ══════════════════════════════════════════════════════════════════════════════
# DEVELOPMENT WITH AWS SERVICES — Mixed difficulty
# ══════════════════════════════════════════════════════════════════════════════
questions += [
  {"question_text":"A developer needs to implement a dead letter queue for an asynchronous Lambda invocation (not SQS-triggered). Where do they configure the DLQ?","options":["On the SQS queue that triggers the Lambda function","On the Lambda function's asynchronous invocation configuration (destination on failure)","On the IAM role attached to the Lambda function","On the event source that invokes the Lambda function asynchronously"],"correct_answer":"On the Lambda function's asynchronous invocation configuration (destination on failure)","explanation":"For async Lambda invocations (S3 events, SNS, EventBridge), configure the DLQ or on-failure destination on the function itself (not on a queue). Lambda retries twice, then sends the event to the configured DLQ or failure destination.","memory_technique":"Async Lambda DLQ = Configured on the function, not a queue. Function → Async invocation config → On failure → SQS DLQ or EventBridge. Retries 2x then DLQ.","topic_area":"Development with AWS Services","difficulty_level":3,"it_context_mapping":"Async invocation DLQs are like undeliverable message handlers — capturing events that couldn't be processed after all retries."},
  {"question_text":"A developer is using API Gateway REST API and needs to validate request bodies against a JSON schema before the request reaches the Lambda function. How should they implement this?","options":["Add validation logic at the beginning of the Lambda function handler","Create a request model in API Gateway and enable request validation on the method","Use a Lambda authorizer to validate the request body before forwarding","Configure API Gateway WAF rules to validate JSON structure"],"correct_answer":"Create a request model in API Gateway and enable request validation on the method","explanation":"API Gateway request models define JSON schemas. When request validation is enabled, API Gateway validates the body against the model before invoking Lambda. Invalid requests get a 400 response without consuming Lambda invocations.","memory_technique":"API Gateway request validation = Schema check before Lambda runs. Invalid body → 400 immediately. No Lambda invocation. Saves cost and reduces code.","topic_area":"Development with AWS Services","difficulty_level":3,"it_context_mapping":"API Gateway request validation is like schema validation middleware — rejecting malformed requests at the gateway before they reach business logic."},
  {"question_text":"A developer needs to implement a long-polling pattern where clients wait up to 20 seconds for new messages. API Gateway has a 29-second timeout. What is the best serverless implementation?","options":["Use API Gateway with a Lambda function that polls SQS with WaitTimeSeconds=20 and returns results","Use API Gateway WebSocket API where the server pushes messages when available","Use CloudFront with a long cache TTL to reduce the number of polling requests","Use Step Functions with a Wait state that pauses for 20 seconds before checking for messages"],"correct_answer":"Use API Gateway with a Lambda function that polls SQS with WaitTimeSeconds=20 and returns results","explanation":"SQS long polling (WaitTimeSeconds=20) blocks until a message arrives or the timeout expires. The Lambda function calls ReceiveMessage with WaitTimeSeconds=20, returns any messages found. Total time fits within API Gateway's 29s limit.","memory_technique":"Long polling = SQS WaitTimeSeconds + Lambda + API Gateway. Client waits, Lambda polls SQS (up to 20s), returns messages or empty. Fits in 29s API Gateway timeout.","topic_area":"Development with AWS Services","difficulty_level":4,"it_context_mapping":"Long polling is the standard pattern for near-real-time updates without WebSockets — the server holds the connection until data is available."},
  {"question_text":"A developer needs to implement a write-behind cache pattern where writes go to ElastiCache first and are asynchronously persisted to DynamoDB. What risk must they mitigate?","options":["Cache entries may expire before being persisted — use DynamoDB Streams to detect missing writes","Data loss if the cache node fails before async persistence completes — use Redis AOF persistence and a reliable flush mechanism","DynamoDB throttling may cause the async writes to back up indefinitely","ElastiCache doesn't support write operations — it's read-only by design"],"correct_answer":"Data loss if the cache node fails before async persistence completes — use Redis AOF persistence and a reliable flush mechanism","explanation":"Write-behind caches risk data loss if the cache fails before flushing to the database. Mitigate with: Redis AOF (append-only file) for durability, Multi-AZ replication, and a reliable flush mechanism (Lambda on schedule or stream).","memory_technique":"Write-behind risk = Data loss on cache failure. Mitigate: Redis AOF + Multi-AZ + reliable flush. Or: accept the risk for non-critical data. Trade durability for write speed.","topic_area":"Development with AWS Services","difficulty_level":5,"it_context_mapping":"Write-behind caching trades durability for performance — the same tradeoff as async replication in databases."},
  {"question_text":"A developer's Lambda function needs to process records from a Kinesis Data Stream. The stream has 4 shards. What is the maximum number of concurrent Lambda invocations for this stream?","options":["4 — one Lambda invocation per shard (default behaviour)","Unlimited — Lambda scales independently of shard count","40 — 10 concurrent invocations per shard with parallelisation factor","The number equals the batch size multiplied by the shard count"],"correct_answer":"4 — one Lambda invocation per shard (default behaviour)","explanation":"By default, Lambda processes one batch per shard concurrently (4 shards = 4 concurrent invocations). You can increase this with ParallelizationFactor (up to 10 per shard), giving a maximum of 40 concurrent invocations for 4 shards.","memory_technique":"Kinesis + Lambda: Default = 1 invocation per shard. ParallelizationFactor (1-10) multiplies it. 4 shards × factor 10 = 40 max concurrent. More shards = more parallelism.","topic_area":"Development with AWS Services","difficulty_level":4,"it_context_mapping":"Kinesis shard-based parallelism is like partition-based consumer groups in Kafka — each partition/shard has a limited number of concurrent consumers."},
  {"question_text":"A developer needs to implement a GraphQL API that aggregates data from multiple microservices (user service, order service, inventory service). What AWS service simplifies this?","options":["API Gateway with multiple Lambda integrations mapped to different GraphQL resolvers","AWS AppSync with pipeline resolvers that chain multiple data source calls in sequence","Amazon EventBridge to aggregate events from all services into a unified response","Step Functions to orchestrate calls to all services and combine results"],"correct_answer":"AWS AppSync with pipeline resolvers that chain multiple data source calls in sequence","explanation":"AppSync pipeline resolvers chain multiple functions (data source calls) in sequence. Each function can call a different service (DynamoDB, Lambda, HTTP endpoint). The pipeline combines results into a single GraphQL response.","memory_technique":"AppSync pipeline resolvers = Chain multiple data sources per field. User from DynamoDB + orders from Lambda + inventory from HTTP. One GraphQL query, multiple backends.","topic_area":"Development with AWS Services","difficulty_level":4,"it_context_mapping":"AppSync pipeline resolvers are like GraphQL DataLoader — aggregating data from multiple sources into a single response."},
]

# ══════════════════════════════════════════════════════════════════════════════
# SECURITY — Mixed difficulty
# ══════════════════════════════════════════════════════════════════════════════
questions += [
  {"question_text":"A developer needs to implement API key rotation for a third-party service without downtime. The API key is stored in Secrets Manager. What is the safest rotation approach?","options":["Update the secret value directly — all Lambda functions will get the new key on next invocation","Use Secrets Manager's multi-version capability: create the new key as AWSPENDING, verify it works, then promote to AWSCURRENT","Create a new secret with the new key and update all Lambda environment variables to point to it","Store both old and new keys in the secret and have the application try both on each request"],"correct_answer":"Use Secrets Manager's multi-version capability: create the new key as AWSPENDING, verify it works, then promote to AWSCURRENT","explanation":"Secrets Manager rotation uses staging labels: AWSCURRENT (active) and AWSPENDING (new). The rotation function creates the new key as AWSPENDING, tests it, then promotes it to AWSCURRENT. The old key remains accessible briefly for in-flight requests.","memory_technique":"Secrets Manager rotation stages: AWSPENDING (new, testing) → AWSCURRENT (promoted, active) → AWSPREVIOUS (old, brief grace period). Zero-downtime rotation.","topic_area":"Security","difficulty_level":4,"it_context_mapping":"Staged secret rotation is like blue/green deployment for credentials — the new credential is verified before becoming active."},
  {"question_text":"A developer's application needs to verify that an incoming webhook request actually came from a specific third-party service (not a spoofed request). What verification method should they implement?","options":["Check that the request comes from the third-party's known IP addresses","Verify the HMAC signature in the request header using the shared webhook secret","Require the third-party to authenticate with an API key in the request header","Check the User-Agent header matches the third-party service's known value"],"correct_answer":"Verify the HMAC signature in the request header using the shared webhook secret","explanation":"Webhook signature verification: the sender computes HMAC-SHA256 of the request body using a shared secret and includes it in a header. The receiver recomputes the HMAC and compares. This proves the request came from someone who knows the secret.","memory_technique":"Webhook verification = HMAC signature. Sender signs body with shared secret. Receiver recomputes and compares. Proves authenticity. IP checks are unreliable (can be spoofed or change).","topic_area":"Security","difficulty_level":3,"it_context_mapping":"HMAC webhook verification is the standard pattern used by GitHub, Stripe, and Slack — proving request authenticity without exposing the secret."},
  {"question_text":"A developer needs to implement field-level encryption where different fields in a DynamoDB item are encrypted with different KMS keys (HR data with HR key, finance data with finance key). Why would they do this?","options":["To improve encryption performance by parallelising encryption across multiple keys","To implement separation of duties — HR team can only decrypt HR fields, finance team can only decrypt finance fields","To comply with a requirement that each field must use a unique encryption key","To enable key rotation on a per-field basis without re-encrypting the entire item"],"correct_answer":"To implement separation of duties — HR team can only decrypt HR fields, finance team can only decrypt finance fields","explanation":"Field-level encryption with different KMS keys enforces separation of duties at the cryptographic level. Even with full DynamoDB access, a user can only decrypt fields whose KMS key they have permission to use. True data compartmentalisation.","memory_technique":"Field-level encryption + different keys = Cryptographic access control. Full table access ≠ full data access. Each key = access to specific fields only. Separation of duties.","topic_area":"Security","difficulty_level":5,"it_context_mapping":"Field-level encryption with separate keys is like column-level security in databases — different teams can access different columns based on their key access."},
  {"question_text":"A developer's Lambda function needs to call AWS services but is running in a VPC with no internet access and no VPC endpoints. What error will they see?","options":["AccessDeniedException — the function's IAM role is invalid without internet connectivity","TimeoutError — the SDK call will hang until the Lambda function times out","NetworkingError — the SDK will immediately fail with a DNS resolution error","The function will work normally — IAM authentication doesn't require internet access"],"correct_answer":"TimeoutError — the SDK call will hang until the Lambda function times out","explanation":"AWS SDK calls need network access to reach AWS service endpoints. In a VPC without internet (no NAT) or VPC endpoints, the TCP connection attempt hangs until timeout. The error appears as a timeout, not an immediate failure.","memory_technique":"Lambda in VPC + no internet + no VPC endpoint = SDK calls timeout. Not immediate error — TCP SYN hangs. Fix: Add VPC endpoint for the service or NAT Gateway.","topic_area":"Security","difficulty_level":3,"it_context_mapping":"This is a network connectivity issue — the application can't reach the service endpoint, resulting in connection timeouts rather than immediate errors."},
  {"question_text":"A developer needs to implement a secure file upload flow where the client uploads directly to S3 but the server must validate the file type and size before accepting it. What approach works?","options":["Generate a pre-signed POST with conditions that restrict content-type and content-length-range","Use a Lambda@Edge function to inspect the upload as it passes through CloudFront","Have the client upload to the server first for validation, then the server uploads to S3","Use S3 Object Lambda to validate the file during the upload process"],"correct_answer":"Generate a pre-signed POST with conditions that restrict content-type and content-length-range","explanation":"Pre-signed POST policies include conditions: content-type must match allowed types, content-length-range restricts file size. S3 enforces these server-side — uploads violating conditions are rejected with 403. No server-side proxy needed.","memory_technique":"Pre-signed POST + conditions = Server-enforced upload rules. Content-type, size limits, key prefix — all enforced by S3. Client uploads directly, S3 validates.","topic_area":"Security","difficulty_level":4,"it_context_mapping":"Pre-signed POST conditions are like server-side form validation — the storage service enforces constraints without the application handling the upload."},
]

# ══════════════════════════════════════════════════════════════════════════════
# DEPLOYMENT — Mixed difficulty
# ══════════════════════════════════════════════════════════════════════════════
questions += [
  {"question_text":"A developer needs to implement a rollback mechanism for a serverless application where the database schema has changed. CloudFormation can roll back infrastructure but not data migrations. What pattern should they use?","options":["Always use backward-compatible schema changes (additive only) so rollback doesn't require data migration","Use CloudFormation Custom Resources to run forward and backward migration scripts","Implement a two-phase deployment: deploy schema changes first, then deploy code changes separately","Take a database snapshot before deployment and restore it on rollback"],"correct_answer":"Always use backward-compatible schema changes (additive only) so rollback doesn't require data migration","explanation":"The expand-and-contract pattern: (1) Add new columns/tables (expand) — backward compatible. (2) Deploy new code that uses new schema. (3) Later, remove old columns (contract). Rollback at any point is safe because old code still works with the expanded schema.","memory_technique":"Expand-and-contract = Safe schema evolution. Add new (expand) → deploy new code → remove old (contract). Rollback-safe at every step. Never break backward compatibility.","topic_area":"Deployment","difficulty_level":5,"it_context_mapping":"Expand-and-contract is the standard pattern for zero-downtime schema migrations — used by GitHub, Facebook, and other large-scale systems."},
  {"question_text":"A developer's CodeBuild project needs to build a Docker image and push it to ECR. The build is failing with 'no basic auth credentials' when pushing. What is missing?","options":["The CodeBuild service role needs ecr:GetAuthorizationToken and ecr:PutImage permissions, and the buildspec must run aws ecr get-login-password","The ECR repository doesn't exist yet — CodeBuild can't create repositories automatically","The Docker daemon isn't running in the CodeBuild environment — enable privileged mode","The CodeBuild project needs a VPC configuration to access ECR's private endpoint"],"correct_answer":"The CodeBuild service role needs ecr:GetAuthorizationToken and ecr:PutImage permissions, and the buildspec must run aws ecr get-login-password","explanation":"Pushing to ECR requires: (1) IAM permissions for ecr:GetAuthorizationToken and ecr:BatchCheckLayerAvailability/PutImage. (2) Running 'aws ecr get-login-password | docker login' in the buildspec to authenticate Docker with ECR.","memory_technique":"ECR push from CodeBuild: IAM permissions (GetAuthorizationToken + PutImage) + docker login via get-login-password in buildspec. Missing either = 'no basic auth credentials'.","topic_area":"Deployment","difficulty_level":3,"it_context_mapping":"ECR authentication is like Docker Hub login — you need to authenticate before pushing images, and the build environment needs the right credentials."},
  {"question_text":"A developer wants to test CloudFormation template changes without actually modifying resources. What feature allows them to preview changes safely?","options":["CloudFormation dry-run mode that simulates the entire deployment without creating resources","CloudFormation Change Sets that show exactly which resources will be added, modified, or replaced","CloudFormation template validation that checks syntax and resource compatibility","CloudFormation stack policies that prevent changes to specific resources"],"correct_answer":"CloudFormation Change Sets that show exactly which resources will be added, modified, or replaced","explanation":"Change Sets preview what CloudFormation will do: which resources are added, modified, replaced, or deleted. You review the change set, then execute it or discard it. This prevents surprises during stack updates.","memory_technique":"Change Set = Preview before apply. Shows: Add, Modify, Replace, Delete for each resource. Review → Execute or Discard. No surprises.","topic_area":"Deployment","difficulty_level":2,"it_context_mapping":"Change Sets are like terraform plan — showing what will change before actually applying the changes."},
  {"question_text":"A developer needs to implement a deployment pipeline that deploys the same application to 3 AWS regions sequentially (us-east-1 first, then eu-west-1, then ap-southeast-1) with validation between each. What CodePipeline feature enables this?","options":["Use a single deploy stage with 3 parallel actions targeting different regions","Use sequential deploy stages with a manual approval action between each region deployment","Use CodePipeline cross-region actions to deploy to multiple regions in a single stage","Use 3 separate CodePipeline pipelines triggered sequentially via EventBridge"],"correct_answer":"Use sequential deploy stages with a manual approval action between each region deployment","explanation":"Sequential stages ensure ordered deployment: Stage 1 deploys to us-east-1, Stage 2 has approval + deploy to eu-west-1, Stage 3 has approval + deploy to ap-southeast-1. Each approval gate validates the previous region before proceeding.","memory_technique":"Sequential multi-region: Stage per region + approval between. Deploy region 1 → validate → approve → deploy region 2 → validate → approve → deploy region 3. Controlled rollout.","topic_area":"Deployment","difficulty_level":4,"it_context_mapping":"Sequential multi-region deployment is like a phased rollout — deploying to one region at a time with validation gates between each."},
  {"question_text":"A developer is using Elastic Beanstalk and needs to configure the application to use a specific Node.js version and install OS-level packages. What is the correct approach?","options":["SSH into the EC2 instances and manually install the packages after deployment","Use a .ebextensions/packages.config file to specify yum/apt packages and set the Node.js platform version in the environment configuration","Create a custom AMI with all packages pre-installed and configure Beanstalk to use it","Include all OS packages in the application's package.json dependencies"],"correct_answer":"Use a .ebextensions/packages.config file to specify yum/apt packages and set the Node.js platform version in the environment configuration","explanation":".ebextensions config files can install OS packages (packages key with yum/apt), run commands, create files, and configure services. The platform version (Node.js version) is set in the environment configuration or .elasticbeanstalk/config.yml.","memory_technique":".ebextensions = Customise Beanstalk environment. packages: install OS deps. commands: run scripts. files: create configs. Platform version = Node.js/Python version.","topic_area":"Deployment","difficulty_level":3,"it_context_mapping":".ebextensions are like Dockerfile RUN commands — customising the environment with additional packages and configuration."},
]

# ══════════════════════════════════════════════════════════════════════════════
# TROUBLESHOOTING AND OPTIMIZATION — Mixed difficulty
# ══════════════════════════════════════════════════════════════════════════════
questions += [
  {"question_text":"A developer's Lambda function uses Python and imports a large library (pandas + numpy) causing 5-second cold starts. They can't use Provisioned Concurrency due to cost. What other optimisations can reduce cold start time?","options":["Use a Lambda Layer for pandas/numpy compiled for the Lambda runtime (Amazon Linux 2)","Switch to the arm64 (Graviton2) architecture which has faster cold starts for Python","Use lazy imports — only import pandas inside the handler function when actually needed","All of the above — each technique contributes to reducing cold start time"],"correct_answer":"All of the above — each technique contributes to reducing cold start time","explanation":"All three help: (1) Layers with pre-compiled binaries avoid compilation overhead. (2) Graviton2 has ~34% better price-performance and faster init. (3) Lazy imports defer loading until needed — if some invocations don't use pandas, they skip the import entirely.","memory_technique":"Cold start reduction: Layers (pre-compiled) + Graviton2 (faster CPU) + Lazy imports (defer loading) + Smaller package (remove unused). Stack all techniques.","topic_area":"Troubleshooting and Optimization","difficulty_level":4,"it_context_mapping":"These are the same startup optimisation techniques used in any application — pre-compilation, faster hardware, and lazy loading."},
  {"question_text":"A developer's DynamoDB table uses on-demand capacity. They notice that read costs are very high despite low traffic. Investigation shows the application is using Scan operations. What should they do?","options":["Switch to provisioned capacity mode which is cheaper for predictable workloads","Replace Scan operations with Query operations using appropriate partition and sort keys","Add a Global Secondary Index and continue using Scan on the smaller index","Enable DynamoDB Accelerator (DAX) to cache the Scan results"],"correct_answer":"Replace Scan operations with Query operations using appropriate partition and sort keys","explanation":"Scan reads every item in the table (or index), consuming RCUs proportional to table size regardless of result count. Query reads only items matching the partition key — far more efficient. Redesign access patterns to use Query instead of Scan.","memory_technique":"Scan = Read entire table. Query = Read one partition. Scan cost grows with table size. Query cost grows with result size. Always prefer Query. Redesign keys if needed.","topic_area":"Troubleshooting and Optimization","difficulty_level":3,"it_context_mapping":"Scan vs Query is like full table scan vs indexed lookup in SQL — the difference between O(n) and O(log n) for data retrieval."},
  {"question_text":"A developer's application uses SQS and Lambda. They notice that some messages take much longer to process than others, causing the visibility timeout to expire and messages to be redelivered (processed twice). What should they do?","options":["Increase the visibility timeout to accommodate the slowest possible message processing time","Use SQS message timers to delay redelivery of slow messages","Implement dynamic visibility timeout extension — call ChangeMessageVisibility during processing to extend the timeout","Switch to SQS FIFO queues which don't have visibility timeout issues"],"correct_answer":"Implement dynamic visibility timeout extension — call ChangeMessageVisibility during processing to extend the timeout","explanation":"ChangeMessageVisibility extends the timeout while processing is in progress. A background thread or periodic check extends the timeout before it expires. This handles variable processing times without setting an excessively long default timeout.","memory_technique":"Variable processing time → ChangeMessageVisibility. Extend timeout while working. Don't set timeout to worst case (wastes time on failures). Extend dynamically as needed.","topic_area":"Troubleshooting and Optimization","difficulty_level":4,"it_context_mapping":"Dynamic visibility extension is like lease renewal in distributed systems — extending the lock while work is in progress rather than setting a fixed long timeout."},
  {"question_text":"A developer's API Gateway returns 429 Too Many Requests to some clients during peak traffic. The Lambda function has plenty of concurrency available. What is throttling the requests?","options":["API Gateway has account-level throttle limits (10,000 RPS default) that are being exceeded","The API Gateway stage has a throttle configuration that's limiting requests per second","Lambda's unreserved concurrency is exhausted causing new invocations to be throttled","The client's API key has exceeded its usage plan quota or rate limit"],"correct_answer":"The API Gateway stage has a throttle configuration that's limiting requests per second","explanation":"API Gateway throttling can occur at multiple levels: account limit (10K RPS), stage-level settings, method-level settings, or usage plan limits per API key. Check stage/method throttle settings first — they're often set lower than the account limit.","memory_technique":"429 from API Gateway: Check throttle settings at stage level, method level, and usage plan level. Account limit is 10K RPS but stage/method limits are often lower.","topic_area":"Troubleshooting and Optimization","difficulty_level":3,"it_context_mapping":"Multi-level throttling is like rate limiting at different layers — each layer can independently limit traffic."},
  {"question_text":"A developer's Lambda function writes to a DynamoDB table and also publishes to an SNS topic. Occasionally the SNS publish fails after the DynamoDB write succeeds, leaving the system in an inconsistent state. How should they fix this?","options":["Wrap both operations in a DynamoDB transaction that includes the SNS publish","Use DynamoDB Streams to trigger a separate Lambda that publishes to SNS — if it fails, the stream retries automatically","Implement a retry loop around the SNS publish with exponential backoff","Use Step Functions to orchestrate the DynamoDB write and SNS publish as separate steps with error handling"],"correct_answer":"Use DynamoDB Streams to trigger a separate Lambda that publishes to SNS — if it fails, the stream retries automatically","explanation":"DynamoDB Streams guarantees that every successful write generates a stream record. A Lambda trigger on the stream publishes to SNS. If the Lambda fails, the stream retries (with the record). This ensures eventual consistency without dual-write risk.","memory_technique":"Dual-write problem: Write DB + publish event can partially fail. Fix: Write DB only → Stream triggers event publish. Stream guarantees delivery. Eventually consistent, always reliable.","topic_area":"Troubleshooting and Optimization","difficulty_level":5,"it_context_mapping":"Using streams to avoid dual writes is the transactional outbox pattern — ensuring database writes and event publications are eventually consistent."},
  {"question_text":"A developer notices that their Lambda function's /tmp directory is not empty on some invocations — it contains files from previous invocations. Is this expected and what should they do?","options":["This is a bug — /tmp should always be empty. File a support ticket with AWS","This is expected — Lambda reuses execution environments. Clean /tmp at the start of each invocation or use unique filenames","This only happens with Provisioned Concurrency — disable it to get clean environments","The function has a memory leak — files in /tmp are consuming the function's memory allocation"],"correct_answer":"This is expected — Lambda reuses execution environments. Clean /tmp at the start of each invocation or use unique filenames","explanation":"Lambda reuses execution environments for performance. /tmp persists between invocations in the same environment. This can be useful (caching) or problematic (stale data). Either clean /tmp at the start or use unique filenames per invocation.","memory_technique":"/tmp persists across invocations (same environment). Useful for caching. Dangerous for stale data. Clean at start or use unique names. Never assume /tmp is empty.","topic_area":"Troubleshooting and Optimization","difficulty_level":3,"it_context_mapping":"Lambda /tmp persistence is like a shared temp directory on a server — files from previous requests may still be there."},
]

# ══════════════════════════════════════════════════════════════════════════════
# WRITE OUTPUT — Merge with existing questions
# ══════════════════════════════════════════════════════════════════════════════
out_path = os.path.join(os.path.dirname(__file__), "dva_questions.json")

# Load existing questions
existing = []
if os.path.exists(out_path):
    with open(out_path, "r", encoding="utf-8") as f:
        existing = json.load(f)

# Merge: add new questions that don't already exist (by question_text)
existing_texts = {q["question_text"] for q in existing}
new_count = 0
for q in questions:
    if q["question_text"] not in existing_texts:
        existing.append(q)
        existing_texts.add(q["question_text"])
        new_count += 1

# Write merged output
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(existing, f, indent=2, ensure_ascii=False)

diff_counts  = Counter(q["difficulty_level"] for q in existing)
topic_counts = Counter(q["topic_area"] for q in existing)
print(f"New questions added: {new_count}")
print(f"Total questions in file: {len(existing)}")
print("By difficulty:", dict(sorted(diff_counts.items())))
print("By topic:", dict(sorted(topic_counts.items())))
