"""
Question bank generator — 500 curated AWS Cloud Practitioner exam questions.
All options are balanced in length so the correct answer cannot be identified by length alone.
Run this script to regenerate questions.json.
"""
import json, os
from collections import Counter

questions = []

# ══════════════════════════════════════════════════════════════════════════════
# CLOUD CONCEPTS — Difficulty 1
# ══════════════════════════════════════════════════════════════════════════════
questions += [
  {"question_text":"What does 'elasticity' mean in cloud computing?","options":["The ability to encrypt data at rest and in transit automatically","The ability to scale resources up or down based on demand","The ability to deploy applications across multiple regions","The ability to migrate workloads between cloud providers"],"correct_answer":"The ability to scale resources up or down based on demand","explanation":"Elasticity means the cloud can automatically provision and de-provision resources to match current demand, avoiding over-provisioning or under-provisioning.","memory_technique":"Elastic band — stretches when you need more, shrinks when you don't.","topic_area":"Cloud Concepts","difficulty_level":1,"it_context_mapping":"Traditional IT required buying peak capacity upfront. Elasticity replaces that with automatic scaling."},
  {"question_text":"Which of the following is a key advantage of cloud computing?","options":["Requires more staff to manage infrastructure on-site","Provides the ability to deploy globally in minutes","Demands higher upfront capital investment for hardware","Offers fixed capacity that cannot be changed dynamically"],"correct_answer":"Provides the ability to deploy globally in minutes","explanation":"Cloud providers have infrastructure in regions worldwide. You can deploy your application globally in minutes rather than months of procurement and setup.","memory_technique":"Cloud = instant global reach. On-premises = months of shipping and racking servers.","topic_area":"Cloud Concepts","difficulty_level":1,"it_context_mapping":"Deploying to a new country traditionally required leasing data center space, shipping hardware, and hiring local staff."},
  {"question_text":"What is the primary benefit of pay-as-you-go cloud pricing?","options":["You receive a dedicated physical server at no extra cost","You must commit to a minimum three-year usage contract","You pay only for the compute resources you actually consume","You pay a fixed monthly fee regardless of actual usage"],"correct_answer":"You pay only for the compute resources you actually consume","explanation":"Pay-as-you-go means you are billed only for what you use — compute seconds, storage gigabytes, data transferred — with no idle costs.","memory_technique":"Like a utility bill — you pay for the electricity you use, not for the capacity of the grid.","topic_area":"Cloud Concepts","difficulty_level":1,"it_context_mapping":"Traditional IT required paying for servers whether they were busy or idle."},
  {"question_text":"What are the three cloud deployment models?","options":["Development, Staging, and Production environments","Infrastructure, Platform, and Software as a Service","Public, Private, and Hybrid cloud deployments","Compute, Storage, and Networking resource types"],"correct_answer":"Public, Private, and Hybrid cloud deployments","explanation":"Public cloud resources are owned by a third-party provider. Private cloud is dedicated to one organisation. Hybrid combines both.","memory_technique":"PPH — Public, Private, Hybrid. Like housing: apartment (public), owned home (private), or both (hybrid).","topic_area":"Cloud Concepts","difficulty_level":1,"it_context_mapping":"Most enterprises use hybrid cloud — keeping sensitive workloads on-premises while using public cloud for scalable workloads."},
  {"question_text":"What does IaaS stand for in cloud computing?","options":["Integration as a Service for connecting applications","Infrastructure as a Service for virtualised resources","Intelligence as a Service for machine learning models","Internet as a Service for network connectivity"],"correct_answer":"Infrastructure as a Service for virtualised resources","explanation":"IaaS provides virtualised computing resources over the internet — servers, storage, and networking — that you manage yourself. Amazon EC2 is an example.","memory_technique":"IaaS = I am a Server. You get the raw infrastructure and manage everything above the hypervisor.","topic_area":"Cloud Concepts","difficulty_level":1,"it_context_mapping":"IaaS is equivalent to renting rack space in a colocation facility, but virtualised."},
  {"question_text":"What does SaaS stand for in cloud computing?","options":["Storage as a Service for managing data archives","Security as a Service for threat detection tools","Software as a Service for fully managed applications","Serverless as a Service for event-driven compute"],"correct_answer":"Software as a Service for fully managed applications","explanation":"SaaS delivers fully managed software applications over the internet. The provider manages everything — infrastructure, OS, middleware, and the application itself.","memory_technique":"SaaS = Someone else's App Service. You just use the software; someone else runs it.","topic_area":"Cloud Concepts","difficulty_level":1,"it_context_mapping":"SaaS replaces installed software — like using Microsoft 365 in a browser instead of installing Office on every PC."},
  {"question_text":"Which AWS support plan is included at no cost for all accounts?","options":["The Developer plan with email-based technical support","The Business plan with 24/7 phone and chat access","The Enterprise plan with a Technical Account Manager","The Basic plan with documentation and health dashboard"],"correct_answer":"The Basic plan with documentation and health dashboard","explanation":"The Basic support plan is free for all AWS accounts. It includes access to documentation, whitepapers, limited Trusted Advisor checks, and the AWS Health Dashboard.","memory_technique":"Basic = free baseline. Everyone gets it automatically when they create an AWS account.","topic_area":"Cloud Concepts","difficulty_level":1,"it_context_mapping":"Basic support is like the free tier of a software product — enough to get started, but you pay more for faster response times."},
  {"question_text":"What is an AWS Region?","options":["A single data center with redundant power supplies","A virtual private network segment within your account","A geographic area containing multiple Availability Zones","A collection of edge locations for content delivery"],"correct_answer":"A geographic area containing multiple Availability Zones","explanation":"An AWS Region is a physical location in the world containing multiple Availability Zones. Each Region is completely independent, providing fault isolation.","memory_technique":"Region = Country. AZ = City within that country. Multiple cities make a country.","topic_area":"Cloud Concepts","difficulty_level":1,"it_context_mapping":"Regions are equivalent to separate data center campuses in different cities."},
  {"question_text":"What is the AWS global network of edge locations used for?","options":["Running EC2 instances for compute-intensive workloads","Storing relational databases with low-latency access","Delivering cached content to users via CloudFront CDN","Managing IAM users and their access permissions"],"correct_answer":"Delivering cached content to users via CloudFront CDN","explanation":"AWS edge locations are part of the CloudFront CDN network. They cache content close to end users, reducing latency by serving requests from the nearest edge location.","memory_technique":"Edge = at the edge of the network, closest to users. Like a local warehouse vs. a central distribution center.","topic_area":"Cloud Concepts","difficulty_level":1,"it_context_mapping":"Edge locations are equivalent to CDN PoPs used by Akamai or Cloudflare."},
  {"question_text":"Which statement best describes high availability in AWS?","options":["A system that runs on a single powerful dedicated server","A system designed to minimise downtime through redundancy","A system that only operates during peak business hours","A system that guarantees 100% uptime with no exceptions"],"correct_answer":"A system designed to minimise downtime through redundancy","explanation":"High availability means designing systems with redundancy so that if one component fails, another takes over automatically, minimising downtime.","memory_technique":"HA = Hardly Any downtime. Redundancy is the key — multiple components so one failure doesn't stop everything.","topic_area":"Cloud Concepts","difficulty_level":1,"it_context_mapping":"Traditional HA required expensive redundant hardware. AWS provides HA through multi-AZ deployments at a fraction of the cost."},
  {"question_text":"What does fault tolerance mean in cloud computing?","options":["The ability to detect and log faults in application code","The system continues operating even when components fail","The maximum number of errors a system can record daily","The process of testing systems for bugs before release"],"correct_answer":"The system continues operating even when components fail","explanation":"Fault tolerance means a system continues to function correctly even when one or more of its components fail. It goes beyond high availability by ensuring zero downtime.","memory_technique":"Fault tolerant = tolerates faults without stopping. Like a car with run-flat tyres.","topic_area":"Cloud Concepts","difficulty_level":1,"it_context_mapping":"Fault tolerance in traditional IT required expensive active-active configurations. AWS services like S3 are built with fault tolerance by design."},
  {"question_text":"What does scalability mean in the context of AWS?","options":["The ability to encrypt data using multiple key algorithms","The ability to increase or decrease resources for workloads","The ability to monitor application performance in real time","The ability to automatically back up data to another region"],"correct_answer":"The ability to increase or decrease resources for workloads","explanation":"Scalability is the ability to handle growing or shrinking workloads by adding or removing resources. AWS supports both vertical scaling (bigger instances) and horizontal scaling (more instances).","memory_technique":"Scale = like a scale that adjusts to weight. Add more capacity when load increases.","topic_area":"Cloud Concepts","difficulty_level":1,"it_context_mapping":"Traditional IT scaled by buying bigger servers or adding more servers. AWS makes both fast and cost-effective."},
  {"question_text":"Which is NOT one of the six advantages of cloud computing defined by AWS?","options":["Trade capital expense for variable expense pricing","Benefit from massive economies of scale globally","Stop guessing about infrastructure capacity needs","Eliminate the need for internet connectivity entirely"],"correct_answer":"Eliminate the need for internet connectivity entirely","explanation":"The six advantages are: trade CapEx for OpEx, economies of scale, stop guessing capacity, increase speed and agility, stop spending on data centers, go global in minutes. Internet connectivity is required.","memory_technique":"The six advantages all make cloud BETTER. Eliminating internet would make it impossible.","topic_area":"Cloud Concepts","difficulty_level":1,"it_context_mapping":"These six advantages represent the core business case for cloud migration."},
  {"question_text":"What is the AWS Management Console?","options":["A command-line tool for scripting AWS operations","A web-based interface for accessing and managing services","A mobile application for monitoring resource health","A desktop application for deploying infrastructure code"],"correct_answer":"A web-based interface for accessing and managing services","explanation":"The AWS Management Console is a web-based interface that provides a graphical way to access and manage AWS services. It is one of three ways to interact with AWS (along with CLI and SDKs).","memory_technique":"Management Console = AWS's website dashboard. Point and click to manage your cloud.","topic_area":"Cloud Concepts","difficulty_level":1,"it_context_mapping":"The Management Console is equivalent to a web-based admin portal like the vSphere Web Client or Azure Portal."},
  {"question_text":"What is the AWS global infrastructure composed of?","options":["Only physical servers and storage hardware devices","Regions, Availability Zones, and Edge Locations globally","Virtual machines and containers running on premises","Software-defined networks and firewalls exclusively"],"correct_answer":"Regions, Availability Zones, and Edge Locations globally","explanation":"AWS global infrastructure consists of Regions (geographic areas), Availability Zones (isolated data center clusters within regions), and Edge Locations (CDN endpoints for CloudFront).","memory_technique":"AWS infrastructure = Regions → AZs → Edge Locations. Three tiers of global presence.","topic_area":"Cloud Concepts","difficulty_level":1,"it_context_mapping":"This three-tier structure mirrors traditional IT: regional data centers, redundant facilities, and CDN PoPs."},
]
